#!/bin/sh

#      THIS FILE IS AUTOMATICALLY DISTRIBUTED BY PUPPET
#       ANY LOCAL CHANGES WILL BE OVERWRITTEN
#
iptables="$([ -z "$IPTABLES" ] && echo $IP6TABLES || echo $IPTABLES)" /bin/run-parts -v <%= @name %>.d
